<?php

namespace Database\Seeders;

use App\Models\PractitionerType;
use Illuminate\Database\Seeder;

class PractitionerTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'uuid' => 'pt1-0000-0000-0000-000000000001',
                'name' => 'Dermatologist',
                'description' => 'Specializes in skin, hair, and nail conditions and treatments',
                'category' => 'Medical',
                'color' => '#3b82f6',
                'icon' => 'Stethoscope',
                'active' => true,
                // permissions
                'perm_can_prescribe' => true, 'perm_can_perform_surgery' => false,
                'perm_requires_assistant' => false, 'perm_can_access_medical_records' => true,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => true,
                'perm_can_view_all_patients' => true, 'perm_can_export_data' => true,
                // features
                'feat_needs_before_after_photos' => true, 'feat_needs_dental_chart' => false,
                'feat_needs_skin_analysis' => true, 'feat_needs_meal_plans' => false,
                'feat_needs_exercise_plans' => false, 'feat_needs_laser_settings' => false,
                'feat_needs_xray_management' => false, 'feat_needs_consent_forms' => true,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => true,
                'feat_needs_insurance_billing' => true, 'feat_needs_product_recommendations' => true,
                // scheduling
                'sched_default_appointment_duration' => 45, 'sched_buffer_time_before' => 10,
                'sched_buffer_time_after' => 10, 'sched_max_appointments_per_day' => 16,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => true,
                'required_certifications' => json_encode(['Board Certification in Dermatology', 'Medical License']),
                'allowed_service_categories' => json_encode(['Skincare', 'Injectable', 'Laser Treatment', 'Consultation', 'Diagnostic']),
            ],
            [
                'uuid' => 'pt2-0000-0000-0000-000000000002',
                'name' => 'Laser Specialist',
                'description' => 'Expert in laser-based aesthetic and medical treatments',
                'category' => 'Aesthetic',
                'color' => '#f97316',
                'icon' => 'Zap',
                'active' => true,
                'perm_can_prescribe' => false, 'perm_can_perform_surgery' => false,
                'perm_requires_assistant' => true, 'perm_can_access_medical_records' => true,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => true,
                'perm_can_view_all_patients' => false, 'perm_can_export_data' => false,
                'feat_needs_before_after_photos' => true, 'feat_needs_dental_chart' => false,
                'feat_needs_skin_analysis' => true, 'feat_needs_meal_plans' => false,
                'feat_needs_exercise_plans' => false, 'feat_needs_laser_settings' => true,
                'feat_needs_xray_management' => false, 'feat_needs_consent_forms' => true,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => false,
                'feat_needs_insurance_billing' => false, 'feat_needs_product_recommendations' => false,
                'sched_default_appointment_duration' => 60, 'sched_buffer_time_before' => 15,
                'sched_buffer_time_after' => 15, 'sched_max_appointments_per_day' => 12,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => true,
                'required_certifications' => json_encode(['Laser Safety Certification', 'Aesthetic Medicine Training']),
                'allowed_service_categories' => json_encode(['Laser Treatment', 'Hair Removal', 'Skincare', 'Consultation']),
            ],
            [
                'uuid' => 'pt3-0000-0000-0000-000000000003',
                'name' => 'Nutritionist',
                'description' => 'Provides dietary advice and creates personalized meal plans',
                'category' => 'Wellness',
                'color' => '#10b981',
                'icon' => 'Apple',
                'active' => true,
                'perm_can_prescribe' => false, 'perm_can_perform_surgery' => false,
                'perm_requires_assistant' => false, 'perm_can_access_medical_records' => true,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => false,
                'perm_can_view_all_patients' => false, 'perm_can_export_data' => true,
                'feat_needs_before_after_photos' => true, 'feat_needs_dental_chart' => false,
                'feat_needs_skin_analysis' => false, 'feat_needs_meal_plans' => true,
                'feat_needs_exercise_plans' => false, 'feat_needs_laser_settings' => false,
                'feat_needs_xray_management' => false, 'feat_needs_consent_forms' => false,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => false,
                'feat_needs_insurance_billing' => false, 'feat_needs_product_recommendations' => true,
                'sched_default_appointment_duration' => 60, 'sched_buffer_time_before' => 5,
                'sched_buffer_time_after' => 5, 'sched_max_appointments_per_day' => 10,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => true,
                'required_certifications' => json_encode(['Registered Dietitian', 'Nutrition Certification']),
                'allowed_service_categories' => json_encode(['Nutrition', 'Wellness', 'Consultation']),
            ],
            [
                'uuid' => 'pt4-0000-0000-0000-000000000004',
                'name' => 'Dentist',
                'description' => 'Specializes in oral health, dental procedures, and orthodontics',
                'category' => 'Dental',
                'color' => '#14b8a6',
                'icon' => 'Smile',
                'active' => true,
                'perm_can_prescribe' => true, 'perm_can_perform_surgery' => true,
                'perm_requires_assistant' => true, 'perm_can_access_medical_records' => true,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => true,
                'perm_can_view_all_patients' => true, 'perm_can_export_data' => true,
                'feat_needs_before_after_photos' => true, 'feat_needs_dental_chart' => true,
                'feat_needs_skin_analysis' => false, 'feat_needs_meal_plans' => false,
                'feat_needs_exercise_plans' => false, 'feat_needs_laser_settings' => false,
                'feat_needs_xray_management' => true, 'feat_needs_consent_forms' => true,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => true,
                'feat_needs_insurance_billing' => true, 'feat_needs_product_recommendations' => false,
                'sched_default_appointment_duration' => 60, 'sched_buffer_time_before' => 10,
                'sched_buffer_time_after' => 15, 'sched_max_appointments_per_day' => 14,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => false,
                'required_certifications' => json_encode(['DDS or DMD Degree', 'State Dental License']),
                'allowed_service_categories' => json_encode(['Dental', 'Surgical', 'Consultation', 'Diagnostic']),
            ],
            [
                'uuid' => 'pt5-0000-0000-0000-000000000005',
                'name' => 'Cosmetic Surgeon',
                'description' => 'Performs surgical and non-surgical cosmetic procedures',
                'category' => 'Medical',
                'color' => '#8b5cf6',
                'icon' => 'Scissors',
                'active' => true,
                'perm_can_prescribe' => true, 'perm_can_perform_surgery' => true,
                'perm_requires_assistant' => true, 'perm_can_access_medical_records' => true,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => true,
                'perm_can_view_all_patients' => true, 'perm_can_export_data' => true,
                'feat_needs_before_after_photos' => true, 'feat_needs_dental_chart' => false,
                'feat_needs_skin_analysis' => true, 'feat_needs_meal_plans' => false,
                'feat_needs_exercise_plans' => false, 'feat_needs_laser_settings' => false,
                'feat_needs_xray_management' => true, 'feat_needs_consent_forms' => true,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => true,
                'feat_needs_insurance_billing' => true, 'feat_needs_product_recommendations' => false,
                'sched_default_appointment_duration' => 120, 'sched_buffer_time_before' => 30,
                'sched_buffer_time_after' => 30, 'sched_max_appointments_per_day' => 6,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => true,
                'required_certifications' => json_encode(['Board Certification in Plastic Surgery', 'Medical License', 'Fellowship in Cosmetic Surgery']),
                'allowed_service_categories' => json_encode(['Surgical', 'Injectable', 'Body Contouring', 'Consultation', 'Diagnostic']),
            ],
            [
                'uuid' => 'pt6-0000-0000-0000-000000000006',
                'name' => 'Physical Therapist',
                'description' => 'Specializes in rehabilitation, injury prevention, and movement therapy',
                'category' => 'Therapeutic',
                'color' => '#ef4444',
                'icon' => 'Activity',
                'active' => true,
                'perm_can_prescribe' => false, 'perm_can_perform_surgery' => false,
                'perm_requires_assistant' => false, 'perm_can_access_medical_records' => true,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => false,
                'perm_can_view_all_patients' => false, 'perm_can_export_data' => true,
                'feat_needs_before_after_photos' => false, 'feat_needs_dental_chart' => false,
                'feat_needs_skin_analysis' => false, 'feat_needs_meal_plans' => false,
                'feat_needs_exercise_plans' => true, 'feat_needs_laser_settings' => false,
                'feat_needs_xray_management' => false, 'feat_needs_consent_forms' => false,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => false,
                'feat_needs_insurance_billing' => true, 'feat_needs_product_recommendations' => false,
                'sched_default_appointment_duration' => 60, 'sched_buffer_time_before' => 5,
                'sched_buffer_time_after' => 5, 'sched_max_appointments_per_day' => 12,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => true,
                'required_certifications' => json_encode(['DPT Degree', 'State PT License']),
                'allowed_service_categories' => json_encode(['Physical Therapy', 'Wellness', 'Consultation']),
            ],
            [
                'uuid' => 'pt7-0000-0000-0000-000000000007',
                'name' => 'Esthetician',
                'description' => 'Provides skincare treatments and beauty services',
                'category' => 'Aesthetic',
                'color' => '#ec4899',
                'icon' => 'Sparkles',
                'active' => true,
                'perm_can_prescribe' => false, 'perm_can_perform_surgery' => false,
                'perm_requires_assistant' => false, 'perm_can_access_medical_records' => false,
                'perm_can_create_treatment_plans' => true, 'perm_can_manage_inventory' => true,
                'perm_can_view_all_patients' => false, 'perm_can_export_data' => false,
                'feat_needs_before_after_photos' => true, 'feat_needs_dental_chart' => false,
                'feat_needs_skin_analysis' => true, 'feat_needs_meal_plans' => false,
                'feat_needs_exercise_plans' => false, 'feat_needs_laser_settings' => false,
                'feat_needs_xray_management' => false, 'feat_needs_consent_forms' => false,
                'feat_needs_progress_tracking' => true, 'feat_needs_prescription_management' => false,
                'feat_needs_insurance_billing' => false, 'feat_needs_product_recommendations' => true,
                'sched_default_appointment_duration' => 60, 'sched_buffer_time_before' => 10,
                'sched_buffer_time_after' => 10, 'sched_max_appointments_per_day' => 10,
                'sched_allow_double_booking' => false, 'sched_requires_consultation' => false,
                'required_certifications' => json_encode(['Esthetician License', 'State Cosmetology License']),
                'allowed_service_categories' => json_encode(['Skincare', 'Body Contouring', 'Wellness']),
            ],
        ];

        foreach ($types as $type) {
            PractitionerType::updateOrCreate(['uuid' => $type['uuid']], $type);
        }
    }
}
